// src/Api.tsx
import React from 'react';
import './Api.css';

const Api: React.FC = () => {
  return (
    <div className="api">
      <div className="api__section">
        <h1 className="api__section__header">API</h1>
        <p className="api__section__description">
          Set an <pre>Accept</pre> header to tailor the <pre>Content-Type</pre> of the response.
        </p>
        <ul>
          <li><pre>text/plain</pre></li>
          <li><pre>text/html</pre></li>
          <li><pre>text/xml</pre></li>
          <li><pre>application/json</pre></li>
        </ul>
      </div>

      <div className="api__section">
        <h2 className="api__section__header">UUID v1</h2>
        <p className="api__section__description">
          Universally Unique Identifier generated using a timestamp.
        </p>
        <p className="api__section__url"><pre>GET</pre><pre>https://uuid.app/api/v1[/$count]</pre></p>
        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Type</th>
              <th>Description</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><pre>$count</pre></td>
              <td><pre>number</pre></td>
              <td>Number of UUIDs to generate</td>
              <td><pre>1</pre></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="api__section">
        <h2 className="api__section__header">UUID v4</h2>
        <p className="api__section__description">
          Universally Unique Identifier generated randomly.
        </p>
        <p className="api__section__url"><pre>GET</pre><pre>https://uuid.app/api/v4[/$count]</pre></p>
        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Type</th>
              <th>Description</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><pre>$count</pre></td>
              <td><pre>number</pre></td>
              <td>Number of UUIDs to generate</td>
              <td><pre>1</pre></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="api__section">
        <h2 className="api__section__header">UUID v5</h2>
        <p className="api__section__description">
          Universally Unique Identifier generated by hasing a namespace and value.
        </p>
        <p className="api__section__url"><pre>GET</pre><pre>https://uuid.app/api/v5[/$namespace]/$value</pre></p>
        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Type</th>
              <th>Description</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><pre>$namespace</pre></td>
              <td><pre>uuid</pre></td>
              <td>Namespace used to hash</td>
              <td>URL or DNS default</td>
            </tr>
            <tr>
              <td><pre>$value</pre></td>
              <td><pre>string</pre></td>
              <td>Value to hash</td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default Api;

// src/routes/api/index.svelte
<script lang="ts">
	import Button from '../../components/button.svelte';
</script>

<svelte:head>
	<title>uuid api</title>
</svelte:head>

<main
	class="
		flex flex-col items-center justify-center h-screen text-left
		text-white
	"
>
	<div>
		<div class="
			hidden
			sm:block
			self-start
			py-4
		">
			<a href="/" class="
				p-2
				bg-black-500
				transition-colors
				text-purple-500
				hover:text-white
				hover:bg-purple-500
				ring-2 ring-purple-500
				rounded-lg
				inline-block
			">
				<svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 17l-5-5m0 0l5-5m-5 5h12" />
				</svg>
			</a>
		</div>

		<div class="
			p-6
			bg-black-500
			ring-2 ring-purple-500
			rounded-lg overflow-hidden
		">
			<section>
				<h1 class="text-2xl sm:text-3xl">API</h1>
				<p>
					Set an <code>Accept</code> header to tailor the <code>Content-Type</code> of the response.
				</p>
				<ul>
					<li><code>text/plain</code></li>
					<li><code>text/html</code></li>
					<li><code>text/xml</code></li>
					<li><code>application/json</code></li>
				</ul>

			</section>

			<section>
				<h2>UUID v1</h2>
				<p>
					Universally Unique Identifier generated using a timestamp.
				</p>
				<p><code>GET https://uuid.app/api/v1[?count=$count]</code></p>
				<table>
					<thead>
						<tr>
							<th>Variable</th>
							<th>Type</th>
							<th>Description</th>
							<th>Default</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><code>$count</code></td>
							<td><code>number</code></td>
							<td>Number of UUIDs to generate</td>
							<td><code>1</code></td>
						</tr>
					</tbody>
				</table>
			</section>

			<section>
				<h2>UUID v4</h2>
				<p>
					Universally Unique Identifier generated randomly.
				</p>
				<p><code>GET https://uuid.app/api/v4[?count=$count]</code></p>
				<table>
					<thead>
						<tr>
							<th>Variable</th>
							<th>Type</th>
							<th>Description</th>
							<th>Default</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><code>$count</code></td>
							<td><code>number</code></td>
							<td>Number of UUIDs to generate</td>
							<td><code>1</code></td>
						</tr>
					</tbody>
				</table>
			</section>

			<!-- <section>
				<h2>UUID v5</h2>
				<p>
					Universally Unique Identifier generated by hasing a namespace and value.
				</p>
				<p><code>GET https://uuid.app/api/v5[/$namespace]/$value</code></p>
				<table>
					<thead>
						<tr>
							<th>Variable</th>
							<th>Type</th>
							<th>Description</th>
							<th>Default</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><code>$namespace</code></td>
							<td><code>uuid</code></td>
							<td>Namespace used to hash</td>
							<td>URL or DNS default</td>
						</tr>
						<tr>
							<td><code>$value</code></td>
							<td><code>string</code></td>
							<td>Value to hash</td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</section> -->
		</div>
	</div>
</main>

<style>
	h2 {
		@apply mt-4 text-xl sm:text-2xl;
	}

	ul {
		@apply list-inside list-disc;
	}

	li {
		@apply leading-loose;
	}

	p {
		@apply leading-loose;
	}

	code {
		@apply p-1 bg-black-900 rounded-lg;
	}

	table {
		@apply mt-1 border-collapse table-auto rounded-lg overflow-hidden;
	}

	th, td {
		@apply p-2 border-2 bg-black-900 border-black-500;
	}
</style>
